/**
 * @file wifi_mgr_events.h
 * @author Kasper Nyhus
 * @brief
 * @version 0.1
 * @date 2023-07-04
 *
 * @copyright Copyright (c) 2023
 *
 */
#pragma once

#include "esp_event.h"

ESP_EVENT_DECLARE_BASE(WIFI_MGR_EVENT);

typedef enum {
    WIFI_MGR_NO_CONNECTION_EVENT,
    WIFI_MGR_CONNECTED_EVENT,
    WIFI_MGR_PROVISION_INIT_EVENT,
    WIFI_MGR_PROVISION_DEINIT_EVENT,
    WIFI_MGR_PROVISION_ACTIVE_EVENT,
    WIFI_MGR_PROVISION_SUCCESS_EVENT,
    WIFI_MGR_PROVISION_FAILED_EVENT,
    WIFI_MGR_PROVISION_TIMEOUT_EVENT,
    WIFI_MGR_PROVISION_ENDED_EVENT,
    WIFI_MGR_DISCONNECTED_EVENT,
    WIFI_MGR_AP_LOST_EVENT,
    WIFI_MGR_ERROR_EVENT,
    WIFI_MGR_EVENT_MAX,
} wifi_mgr_event_t;

static const char* const wifi_mgr_event_name[WIFI_MGR_EVENT_MAX] = {
    "WIFI_MGR_NO_CONNECTION_EVENT",
    "WIFI_MGR_CONNECTED_EVENT",
    "WIFI_MGR_PROVISION_INIT_EVENT",
    "WIFI_MGR_PROVISION_DEINIT_EVENT",
    "WIFI_MGR_PROVISION_ACTIVE_EVENT",
    "WIFI_MGR_PROVISION_SUCCESS_EVENT",
    "WIFI_MGR_PROVISION_FAILED_EVENT",
    "WIFI_MGR_PROVISION_TIMEOUT_EVENT",
    "WIFI_MGR_PROVISION_ENDED_EVENT",
    "WIFI_MGR_DISCONNECTED_EVENT",
    "WIFI_MGR_AP_LOST_EVENT",
    "WIFI_MGR_ERROR_EVENT"
};
